name: dropdown_selection
description: frok rom dropdown_search , fix dialog option size not dynamic issue
version: 0.0.5
homepage: https://github.com/salim-lachdhaf
git: https://github.com/salim-lachdhaf/searchable_dropdown
repository: https://github.com/salim-lachdhaf/searchable_dropdown

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  optional: ^5.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
